In [1]:
import pandas as pd
import numpy as np
# Visualization
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import seaborn as sns
%matplotlib inline

In [2]:
# Load cumilative datasets created in step 1
cumllaborcnty = pd.read_csv('cumllaborcnty.csv')
cumllaborvt = pd.read_csv('cumllaborvt.csv')

In [3]:
cumllaborcnty = pd.melt(cumllaborcnty,id_vars=['Year','County','Type'],var_name='Time', value_name='Count')
cumllaborcnty.head()

,Year,County,Type,Time,Count
0,2017,Addison County,Total Covered - all ownerships,Jan,13094
1,2017,Addison County,Private ownership,Jan,11078
2,2017,Addison County,Goods Producing domain,Jan,3259
3,2017,Addison County,Natural Resources and Mining supersector,Jan,459
4,2017,Addison County,"Agriculture, forestry, fishing and hunting",Jan,421

In [4]:
# There are missing values or occasions where the occurance is too small to show, each we are replacing with NaNs
cumllaborcnty = cumllaborcnty.replace('(c)', np.nan)
cumllaborcnty = cumllaborcnty.replace('-', np.nan)
cumllaborcnty = cumllaborcnty.replace('na', np.nan)
cumllaborcnty = cumllaborcnty.replace(' ', np.nan)
cumllaborcnty = cumllaborcnty.replace('<1', 1)
cumllaborcnty['Count'] = pd.to_numeric(cumllaborcnty['Count'])

In [5]:
cumllaborcnty.head()

,Year,County,Type,Time,Count
0,2017,Addison County,Total Covered - all ownerships,Jan,13094.0
1,2017,Addison County,Private ownership,Jan,11078.0
2,2017,Addison County,Goods Producing domain,Jan,3259.0
3,2017,Addison County,Natural Resources and Mining supersector,Jan,459.0
4,2017,Addison County,"Agriculture, forestry, fishing and hunting",Jan,421.0

In [6]:
# Set up lists of how these are going to be split out into similiar types
monthlist = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

quarterslist = ['Average Employment Qtr 1', 'Average Employment Qtr 2', 'Average Employment Qtr 3', 'Average Employment Qtr 4', 
            'Average Female Employment Qtr 1', 'Average Female Employment Qtr 2','Average Female Employment Qtr 3',
            'Average Female Employment Qtr 4','Total Wages Qtr 1', 'Total Wages 2', 'Total Wages 3', 
            'Total Wages 4','Average Wage Qtr 1', 'Average Wage Qtr 2', 'Average Wage Qtr 3', 
            'Average Wage Qtr 4','Number of Establishments Qtr 1', 'Number of Establishments Qtr 2',
            'Number of Establishments Qtr 3', 'Number of EstablishmentsQtr 4'
           ]

annuallist = ['Average Employment Annual', 'Average Female Employment Annual', 'Total Wages Annual',  'Average Wage Annual',
           'Number of Establishments Annual'
          ]

In [7]:
months = cumllaborcnty[cumllaborcnty['Time'].isin(monthlist)].copy()
quarters = cumllaborcnty[cumllaborcnty['Time'].isin(quarterslist)].copy()
annual = cumllaborcnty[cumllaborcnty['Time'].isin(annuallist)].copy()

In [8]:
quarters.head()

,Year,County,Type,Time,Count
114156,2017,Addison County,Total Covered - all ownerships,Average Employment Qtr 1,13162.0
114157,2017,Addison County,Private ownership,Average Employment Qtr 1,11121.0
114158,2017,Addison County,Goods Producing domain,Average Employment Qtr 1,3270.0
114159,2017,Addison County,Natural Resources and Mining supersector,Average Employment Qtr 1,474.0
114160,2017,Addison County,"Agriculture, forestry, fishing and hunting",Average Employment Qtr 1,437.0

In [9]:
quarters['Quarter'] = np.nan

In [10]:
quarters.loc[quarters['Time'].str.endswith("Qtr 1"), "Quarter"] = "1"
quarters.loc[quarters['Time'].str.endswith("Qtr 2"), "Quarter"] = "2"
quarters.loc[quarters['Time'].str.endswith("Qtr 3"), "Quarter"] = "3"
quarters.loc[quarters['Time'].str.endswith("Qtr 4"), "Quarter"] = "4"
quarters['Time'] = quarters['Time'].str[:-6]

In [11]:
pd.unique(quarters['Time'])

array(['Average Employment', 'Average Female Employment', 'Total Wages',
       'Average Wage', 'Number of Establishments'], dtype=object)

In [12]:
quarters.columns

Index(['Year', 'County', 'Type', 'Time', 'Count', 'Quarter'], dtype='object')

In [16]:
quarters.columns = ['Year', 'County', 'Type', 'Stat', 'Count', 'Quarter']
quarters = quarters[['Year', 'Quarter', 'County', 'Type', 'Stat', 'Count', ]]

In [17]:
quarters.head()

,Year,Quarter,County,Type,Stat,Count
114156,2017,1,Addison County,Total Covered - all ownerships,Average Employment,13162.0
114157,2017,1,Addison County,Private ownership,Average Employment,11121.0
114158,2017,1,Addison County,Goods Producing domain,Average Employment,3270.0
114159,2017,1,Addison County,Natural Resources and Mining supersector,Average Employment,474.0
114160,2017,1,Addison County,"Agriculture, forestry, fishing and hunting",Average Employment,437.0

In [28]:
test = quarters.pivot(columns='Stat', values='Count')

test2 = pd.pivot_table(quarters, values='Count', index=['Year','Quarter','County','Type'], columns=['Stat'])
test2 = test2.reset_index()

In [30]:
test2.head(40)

Stat,Year,Quarter,County,Type,Average Employment,Average Female Employment,Average Wage,Number of Establishments,Total Wages
0,2017,1,Addison County,Accommodation and food services,860.000000,497.375000,3928.166667,75.222222,3373.055556
1,2017,1,Addison County,Administrative and waste services,162.727273,56.090909,6923.000000,58.333333,1121.363636
2,2017,1,Addison County,"Agriculture, forestry, fishing and hunting",532.125000,107.000000,6665.937500,74.277778,3631.437500
3,2017,1,Addison County,"Arts, entertainment, and recreation",109.111111,64.687500,3980.555556,15.888889,437.000000
4,2017,1,Addison County,Construction supersector,636.000000,87.812500,9351.444444,174.666667,5953.166667
5,2017,1,Addison County,Durable Goods manufacturing,1243.944444,418.562500,14225.333333,34.833333,17525.055556
6,2017,1,Addison County,Education and Health Services supersector,3526.722222,2353.875000,9569.055556,130.888889,34188.555556
7,2017,1,Addison County,Educational services,NaN,NaN,NaN,21.166667,NaN
8,2017,1,Addison County,Federal Government,123.611111,NaN,10728.166667,30.888889,1310.444444
9,2017,1,Addison County,Finance and insurance,329.944444,236.125000,11727.277778,40.777778,3872.833333
10,2017,1,Addison County,Financial Activities supersector,411.333333,280.500000,10588.777778,70.833333,4328.944444
11,2017,1,Addison County,Goods Producing domain,3163.944444,859.312500,10967.500000,318.555556,34478.222222
12,2017,1,Addison County,Health care and social assistance,NaN,NaN,NaN,109.722222,NaN
13,2017,1,Addison County,Information supersector,99.833333,53.625000,7194.166667,18.166667,704.166667
14,2017,1,Addison County,Leisure and Hospitality supersector,969.000000,562.062500,3924.611111,91.111111,3810.055556
15,2017,1,Addison County,Local government,1762.277778,1226.562500,7775.333333,61.666667,13634.611111
16,2017,1,Addison County,Management of companies and enterprises,NaN,NaN,NaN,1.000000,NaN
17,2017,1,Addison County,Manufacturing supersector,1971.611111,662.562500,12710.166667,63.833333,24675.222222
18,2017,1,Addison County,Mining,22.125000,2.142857,9832.562500,5.777778,206.687500
19,2017,1,Addison County,Natural Resources and Mining supersector,556.111111,108.937500,6787.055556,80.055556,3849.833333
20,2017,1,Addison County,Non-Durable Goods manufacturing,727.611111,244.000000,9985.444444,29.000000,7150.111111
21,2017,1,Addison County,"Other services, except public administration s...",351.333333,200.000000,6192.833333,108.722222,2183.388889
22,2017,1,Addison County,Private ownership,11614.666667,5684.875000,8958.055556,1217.444444,104404.277778
23,2017,1,Addison County,Professional and Business Services supersector,636.833333,326.187500,11154.166667,204.000000,7143.277778
24,2017,1,Addison County,Professional and technical services,469.277778,270.187500,12152.333333,145.277778,5724.222222
25,2017,1,Addison County,Real estate and rental and leasing,81.500000,44.375000,5854.833333,30.055556,456.055556
26,2017,1,Addison County,Retail trade,1869.277778,891.875000,6761.055556,182.777778,12655.555556
27,2017,1,Addison County,Service Providing domain,8450.666667,4825.562500,8217.833333,898.888889,69926.166667
28,2017,1,Addison County,State government,166.611111,86.375000,10237.722222,11.555556,1688.944444
29,2017,1,Addison County,Total Covered - all ownerships,13667.222222,NaN,8835.555556,1321.555556,121038.444444
30,2017,1,Addison County,"Trade, Transportation, and Utilities supersector",2455.444444,1049.312500,7148.444444,275.166667,17567.722222
31,2017,1,Addison County,Transportation and warehousing,323.428571,91.833333,6391.357143,31.833333,2078.428571
32,2017,1,Addison County,Unspecified industry supersector,NaN,NaN,NaN,NaN,NaN
33,2017,1,Addison County,Utilities,NaN,NaN,NaN,2.111111,NaN
34,2017,1,Addison County,Wholesale trade,297.000000,74.750000,8222.250000,58.444444,2436.750000
35,2017,1,Addison County,released: August 2017,NaN,NaN,NaN,NaN,NaN
36,2017,1,Addison County,released: November 2017,NaN,NaN,NaN,NaN,NaN
37,2017,1,Addison County,released: September 2016,NaN,NaN,NaN,NaN,NaN
38,2017,1,All Other county,Accommodation and food services,38.333333,18.500000,9076.000000,6.555556,327.000000
39,2017,1,All Other county,Administrative and waste services,535.000000,193.214286,8710.062500,108.722222,4798.750000

In [ ]:
# Clean up the column order and then sort everything
months.sort_values(by=['County','Year','Time'])
months.shape

## Exploring the Data

At this point what we have is month over month employment counts for 17 years by industry at various levels. First we are going to tackle the supersectors and see what they look like in box plots. Box plots are a standardized way of displaying the distribution of data based on the five number summary: 
* minimum (bottom T of the line)
* first quartile (bottom of the box)
* median (horizontal line bisecting the box)
* third quartile (top of the box)
* maximum. (top T of the line

In [ ]:
natres = quarters[quarters['Type'] == 'Natural Resources and Mining supersector']

data = natres
sns.boxplot(x='Time', y='Count',  data=data)
plt.xticks(rotation=90)

In [ ]:
data = natres
sns.boxplot(x='Time', y='Count', hue='County',  data=data)
plt.xticks(rotation=45)

In [ ]:
const = months[months['Type'] == 'Construction supersector']

data = const
sns.boxplot(x='Month', y='Count',  data=data)
plt.xticks(rotation=90)

In [ ]:
manf = months[months['Type'] == 'Manufacturing supersector']

data = manf
sns.boxplot(x='Month', y='Count',  data=data)
plt.xticks(rotation=90)

In [ ]:
trade = months[months['Type'] == 'Trade, Transportation, and Utilities supersector']

data = trade
sns.boxplot(x='Month', y='Count',  data=data)
plt.xticks(rotation=90)

In [ ]:
info = months[months['Type'] == 'Information supersector']
data = info
sns.boxplot(x='Month', y='Count', data=data)
plt.xticks(rotation=90)

In [ ]:
fin = months[months['Type'] == 'Financial Activities supersector']
data = fin
sns.boxplot(x='Month', y='Count',  data=data)
plt.xticks(rotation=90)

In [ ]:
busin = months[months['Type'] == 'Professional and Business Services supersector']
data = busin
sns.boxplot(x='Month', y='Count', data=data)
plt.xticks(rotation=90)

In [ ]:
edhealth = months[months['Type'] == 'Education and Health Services supersector']
data = edhealth
sns.boxplot(x='Month', y='Count', data=data)
plt.xticks(rotation=90)

In [ ]:
leis = months[months['Type'] == 'Leisure and Hospitality supersector']
data = leis
sns.boxplot(x='Month', y='Count', data=data)
plt.xticks(rotation=90)

In [ ]:
other = months[months['Type'] == 'Other services, except public administration supersector']
data = other
sns.boxplot(x='Month', y='Count', data=data)
plt.xticks(rotation=90)

In [ ]:
art = months[months['Type'] == 'Arts, entertainment, and recreation']
#art = months[months['Type'] == 'Leisure and Hospitality supersector']

art.head()

In [ ]:
data = art[art['County'] == 'Chittenden County']
sns.boxplot(x='Month', y='Count',   data=data)
plt.xticks(rotation=90)

In [ ]:
data = art[art['County'] == 'Washington County']
sns.boxplot(x='Month', y='Count',   data=data)
plt.xticks(rotation=90)

In [ ]:
data = art
data = data[(data['County'] == 'Bennington County') |
          (data['County'] == 'Washington County') | 
          (data['County'] == 'Chittenden County') | 
          (data['County'] == 'Rutland County')]
sns.boxplot(x='Month', y='Count', hue='County',  data=data)
plt.xticks(rotation=90)

In [ ]:
health = months[months['Type'] == 'Education and Health Services supersector']

In [ ]:
sns.boxplot(x='County', y='Count', data=health)
plt.xticks(rotation=90)

In [ ]:
pd.unique(months['Type'])

In [ ]:
fin = months[months['Type'] == 'Financial Activities supersector']

In [ ]:
sns.boxplot(x='County', y='Count',  data=fin)
plt.xticks(rotation=90)

In [ ]:
tech = months[months['Type'] == 'Professional and Business Services supersector']

In [ ]:
sns.boxplot(x='County', y='Count',  data=tech)
plt.xticks(rotation=90)

In [ ]:
info = months[months['Type'] == 'Information supersector']

In [ ]:
sns.boxplot(x='County', y='Count',  data=info)
plt.xticks(rotation=90)

In [ ]:
healthed = months[months['Type'] == 'Education and Health Services supersector']

In [ ]:
sns.boxplot(x='County', y='Count',  data=healthed)
plt.xticks(rotation=90)

In [ ]:
fed = months[months['Type'] == 'Federal Government']

In [ ]:
sns.boxplot(x='County', y='Count',  data=fed)
plt.xticks(rotation=90)

In [ ]:
state = months[months['Type'] == 'State government']

In [ ]:
sns.boxplot(x='County', y='Count',  data=state)
plt.xticks(rotation=90)